env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:@typescript-eslint/recommended
overrides: []
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
  - simple-import-sort
rules:
  # indent:
  #   - error
  #   - 4
  # linebreak-style:
  #   - error
  #   - windows
  quotes:
    - error
    - single
  semi:
    - error
    - always
  simple-import-sort/imports:
    - warn
  simple-import-sort/exports:
    - warn
