services:
  database:
    environment:
      POSTGRES_DB: ${DatabaseSettings__Name}
      POSTGRES_USER: ${DatabaseSettings__Username}
      POSTGRES_PASSWORD: ${DatabaseSettings__Password}
    expose:
      - 5432
    image: postgres:14.1-alpine
    networks:
      - main
    restart: unless-stopped
    volumes:
      - data:/var/lib/postgresql/data/

  client:
    build: client/
    volumes:
      - static:/app/dist

  server:
    build: server/
    depends_on:
      - database
    env_file:
      - .env
    expose:
      - 8080
    restart: unless-stopped
    networks:
      - main

  nginx:
    build: nginx/
    cap_add:
      - NET_ADMIN
    depends_on:
      - client
    env_file:
      - .env
    ports:
      - 81:81
    restart: unless-stopped
    networks:
      - main
    volumes:
      - static:/static:ro
  
volumes:
  data:
  static:

networks:
  main:
    driver: bridge
